Stabilize torch.topk() behavior
Noble-Lab/casanovo pull request #290
Opened 2024-02-09 00:50 UTC by melihyilmaz

Addresses #284 

To make sure we get the padding token at index  '0'  as the top scoring token for finished beams at each decoding step, I added a small epsilon of `1e-8` to index '0' in `finished_mask` so that it's not zeroed out like the rest of values on the same row. Again, these zero rows correspond to finished beams and we use masking to avoid extending them with new AA tokens.

This seems to resolve the error with minimal/no overhead (I get the same output on both CPU and GPU for the problematic mgf files mentioned in the issue) but unit tests still need to be added (@bittremieux feel free if you get a chance) and I'm open to moving away from `torch.topk()` if there are suggestions for a more robust or elegant solution.

2024-02-10 07:47 UTC, bittremieux requested changes
I still don't find it super elegant, but it might be a practical fix for now. I combined some code to remove a few redundant steps, but the fix is the same.

@melihyilmaz Can you try to come up with a unit test that failed before the fix and runs now? So we can ensure that this is properly tested and avoid regression issues in the future.

2024-02-13 01:01 UTC, melihyilmaz commented
I add a unit test for `_get_topk_beams()` that only passes with the current fix. I also compared results for a small mgf on CPU vs. GPU and those identical now.

2024-02-14 13:17 UTC, bittremieux approved these changes

2024-02-14 13:38 UTC, merged

2024-02-15 21:16 UTC, wsnoble commented
You should be able to install from the dev branch like this:

`pip install git+https://github.com/Noble-Lab/casanovo.git@dev`

2024-02-16 08:37 UTC, bittremieux commented
@lutfia95 We've now released Casanovo v4.1.0 as well that includes this fix, so you can more conveniently now upgrade from PyPI as well.