Automatically download model weights
Noble-Lab/casanovo pull request #68
Opened 2022-08-23 23:40 UTC by bittremieux

Fixes #17.

Model weights files (extension: .ckpt) should be provided as an asset with their corresponding release on GitHub. Model weights will be retrieved by matching release version. If no model weights for an identical release (major, minor, patch), alternative releases
with matching (i) major and minor, or (ii) major versions will be used. If no matching release can be found, no model weights will be downloaded. The model weights will be downloaded to the current working directory.

Note that the GitHub API is limited to 60 requests from the same IP per hour. A log message provides instructions to explicitly specify the model file for subsequent uses.

Review: @wsnoble to check whether this is the desired behavior for the users and the documentation, @wfondrie to check the code.

2022-08-27 22:19 UTC, wfondrie requested changes
This looks like it solves the problem to me. Its a bit complicated and I think it'd be worthwhile to create unit tests for it, perhaps by mocking a response GitHub.

Also, do we have a way to verify that the architecture (number of layers, layer dim, etc) matches the downloaded weights, or to automatically set it?

2022-08-27 22:19 UTC, wfondrie commented on casanovo/casanovo.py
> +    )
**suggestion:** This is pretty ugly. Maybe use `re.compile` above to clean it up? Something like:
```python
version_regex = re.compile(r"(\d+)\.(\d+)\.(\d+)(?:.dev\d+.+)?")
version = tuple(g for g in version_regex.match(__version__).groups())
```

2022-10-11 19:03 UTC, wfondrie commented
It looks like checking the version is failing in GH Actions 🤔

2022-10-11 20:53 UTC, bittremieux commented
I see you removed the `psutil` dependency. This is necessary to correctly set resources on a shared system, such as the cluster. `os.cpu_count()` will give the number of CPUs that are present, `psutil` instead will give the number CPUs that can be used. Thus, if you use `os.cpu_count()` but you requested only a specific number of CPUs, this will make sure that there aren't an excessive number of worker threads (extreme case: on n032 use 40 workers threads when the job only has 1 CPU).

2022-10-11 21:00 UTC, wfondrie commented
Good point @bittremieux, but `psutils.Process.cpu_affinity()` doesn't support MacOS. We need another solution 🤔

2022-10-11 21:02 UTC, wfondrie commented
@bittremieux, would `len(os.sched_getaffinity())` work? https://docs.python.org/3/library/os.html#os.sched_getaffinity

2022-10-11 21:16 UTC, wfondrie commented
Sounds like we may need something like:
```python
import os
import psutils

def n_workers():
    try:
        return len(psutils.Process().cpu_affinity())
    except AttributeError:
        return len(os.sched_getaffinity(0))
```
Or vice versa. Thoughts?

2022-10-11 21:27 UTC, bittremieux commented
Yes, that makes sense. I was unaware of the Mac incompatibility because I don't have a Mac. Likewise, whether it runs on Windows is only from reading StackOverflow and the psutils documentation, not from exactly testing it.

2022-10-11 23:12 UTC, wfondrie commented
Now we're getting a multiprocessing error on Windows 🤦‍♂️

2022-10-26 16:44 UTC, wfondrie approved these changes

2022-11-03 02:59 UTC, merged