Adding graph generation to eval mode of Casanovo
Noble-Lab/casanovo pull request #85
Opened 2022-10-23 05:29 UTC by VarunAnanth2003

If merged, will allow for the generation of an evaluation graph when running casanovo in `eval` mode. The location of the graph is specified with the `--output` CLI option.

THIS CODE IS FULLY FUNCTIONAL but it is **WIP for a few reasons:**

- Due to the nature of running a model in validate vs. predict mode, using the `evaluate` method in `model_runner.py` results in an empty `.mztab` file being created (when a writer is provided) and therefore no information can be discerned from it. To circumvent this, I made the method call in the `evaluate()` method the same as the `predict()` method, allowing for the creation of a valid `.mztab` file. This does not seem optimal as I can see a few reasons this may lead to crashes (i.e running `--eval` on a non `.mgf` file that would otherwise be valid in predict mode). If there is another way around this, that would be great to know.
- Code coverage tests... They don't exist yet! I am unsure of what the final implementation of this functionality will be due to the issues described above so I am unsure about how to write tests since the methods and their locations are in flux.
- inconsistent documentation: The `--eval` mode now needs an output path to work, and this is not consistent with previous implementations.

2022-11-16 19:35 UTC, wfondrie commented
I've been working on this today and I've come to the conclusion that I don't think it's feasible to make the benchmarking more general. The challenge is converting the modification strings from one format to the same used by MassIVE-KB. The major issue with this conversion is that some sources don't include fewer decimal places in their modification strings, making the conversion non-trivial.

@VarunAnanth2003 - how goes removing the actual plots and instead returning a DataFrame? I'll be making some small changes to docstrings and such.

2022-11-16 22:42 UTC, bittremieux commented
Can you give an example of this conversion problem @wfondrie? [spectrum_utils now supports the full ProForma 2.0 specification](https://spectrum-utils.readthedocs.io/en/latest/annotating.html), which is reasonably flexible in the way modifications can be specified. IIRC the MassIVE-style modifications are not fully ProForma-compliant, but can easily be converted by surrounding the masses by square brackets. Could we try to use ProForma as an intermediate representation?

2022-11-16 23:36 UTC, wfondrie commented
That seems like good idea @bittremieux! Here one the current conversions that we're doing in this PR:
```python
    mgf_df["true_seq"] = mgf_df["true_seq"].str.replace(
        "C[57.02]", "C+57.021", regex=False
    )
```
Here, `C[57.02]` is the modification output by Tide (right @VarunAnanth2003?), and `C+57.021` is the equivalent in our MassIVE-KB vocabulary. This example is trivial to convert manually, but difficult otherwise, because we'd need some kind of fuzzy matching scheme. Is there an easy way to convert all of these to proforma?

2022-11-17 01:02 UTC, bittremieux commented
Hmm, the difference in precision makes it a bit challenging. ProForma allows to specify modifications by their mass as `PEPC[+57.021]IDER`, so slightly different than both of those representations. Converting each one to a compatible ProForma string is straightforward, but that won't take care of the different number of decimals.

I guess we could round to the number of decimals from the least precise representation? For that we don't even need ProForma, but maybe that's still useful as a consistent representation. In which case the steps would be:
1. Surround all numeric values by square brackets and always show the sign.
2. Round to a specified number of decimals (2).

Not entirely satisfactory, but it maybe works?

2022-11-18 23:59 UTC, melihyilmaz requested changes
In the context of conversation above around generalized PTM representations but of more immediate practical concern, "C" is represented without its default modification currently impacts precision calculation for 9 species benchmark.

2022-11-18 23:59 UTC, melihyilmaz commented on casanovo/denovo/evaluate.py
> +    mgf_df["true_seq"] = mgf_df["true_seq"].str.replace(
If 'C' not represented with its permanent modification, this implementation fails to match those with 'C+57.021' token predicted by Casanovo

2022-11-18 23:59 UTC, melihyilmaz commented on casanovo/denovo/evaluate.py
> +    with mgf.MGF(mgf_filename) as f_in:
We can generalize this to a list of mgf files rather than a single file at a time

2023-01-17 22:39 UTC, wsnoble commented
We should work on merging this.  I think it will require that Varun write some tests.

2023-01-18 18:09 UTC, melihyilmaz commented
@wfondrie With Wout's proposal for generalizing how modifications are represented, do you think there's a way forward with generalized benchmarking or should we go ahead with the current treatment of modifications?

2023-01-18 18:16 UTC, VarunAnanth2003 commented
I can work on writing tests/finishing this PR after figuring out how to go forward

2023-08-18 17:33 UTC, closed without merging